### ISSUE TITLE
can't connect correctly to a mysql database

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/php-model#3]
so I try to connect to a database 
```php
<?php
require_once 'vendor/autoload.php';

require_once('src/models/functions.php');

$dbCreds = databaseCredentials('.env');

$driver = new \Aternos\Model\Driver\Mysqli\Mysqli($dbCreds['host'], 3306, $dbCreds['user'], $dbCreds['password'], "", $dbCreds['database']);
\Aternos\Model\Driver\DriverRegistry::getInstance()->registerDriver($driver);
?>
```
databaseCredentials looks like this 
```php
function databaseCredentials(string $pathToEnv): array {
    $env = parse_ini_file($pathToEnv);

    $host = $env['HOST'];
    $user = $env['USER'];
    $password = $env['PASSWORD'];
    $database = $env['DATABASE'];

    return ["host" => $host, "user" => $user, "password" => $password, "database" => $database];
}
```
my .env what is in the correct path looks like 
```env
HOST='example.com
USER='d'
PASSWORD='*'
DATABASE='*'
```
I can confirm that the database works fine 

 ```
[::1]:64642 [500]: GET / - Uncaught Error: Call to undefined function Aternos\Model\Driver\Mysqli\mysqli_connect() in \vendor\aternos\model\src\Driver\Mysqli\Mysqli.php:105
Stack trace:
#0 \vendor\aternos\model\src\Driver\Mysqli\Mysqli.php(231): Aternos\Model\Driver\Mysqli\Mysqli->connect()
#1 \vendor\aternos\model\src\GenericModel.php(406): Aternos\Model\Driver\Mysqli\Mysqli->query()
#2 vendor\aternos\model\src\GenericModel.php(460): Aternos\Model\GenericModel::query()
#3 Aternos-guides\index.php(49): Aternos\Model\GenericModel::select()
#4 {main}
  thrown in \vendor\aternos\model\src\Driver\Mysqli\Mysqli.php on line 105

```

if you are missing something that I need to add, just ask me

**Comment by JulianVennen** [comment]
Are you sure that the MySQL php extension is installed and enabled?

**Comment by Dobby-progam** [comment]
it was installed but not enabled, when I enabled it it works fine
